### ISSUE TITLE
"port not specified" on TYT radio firmware flash

### ISSUE THREAD

**Issue by Tyler-2** [v0l/radio_tool#10]
```
~/Repos/radio_tool/build$ ./radio_tool -i ~/Downloads/openrtx_mduv3x0_wrap -f -d 0
Error: Port not specified

~/Repos/radio_tool/build$ ./radio_tool -i ~/Downloads/openrtx_mduv3x0_wrap -f -d 0 -P asdasd
```

It seems that the help output doesn't specify the `-P` option (Only for Ailunce radios?) but that it is still required to pass _something_ to the WriteFirmware function.

**Comment by v0l** [comment]
Yes this is a bug on main maybe you can try use the tagged release `v0.1.1` that one should do the trick for TYT radios

**Comment by v0l** [comment]
@Tyler-2 you could also try to get the latest version from `main` and rebuild, it should work now.

```
git pull
... build
```

**Comment by Tyler-2** [comment]
Thanks @v0l 

I can't test this fix as I had to put the radio I was testing with back into service, sorry! But thanks for the quick resolve.

**Comment by v0l** [comment]
Ok, ill close this now, please re-open if its still an issue for you.
